baseURL = 'https://psychomanatee.pages.dev/'
languageCode = 'en-us'
title = 'Psycho Manatee'

[params]
description = 'Insane and Deathly Comics.'
dateFormat = 'Jan 2, 2006'
comicResizeWidth = 1280
comicThumbResizeWidth = 300
imgFormat = 'jpg'
[params.author]
name = 'Tina Michelle'

[taxonomies]

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[menu.main]]
name = 'About'
pageRef = '/about'
weight = 2

[[menu.main]]
name = 'Archive'
pageRef = '/archive'
weight = 3

[imaging]
resampleFilter = 'Lanczos'
quality = 75
